train_batch_size = 64
val_batch_size = 64

[train_dataset.specific]
name = "dataset1"
mode = "train"
epoch_scale_factor = 1.0
kfold_N = 5
kfold_I = 0

[[val_datasets]]
[val_datasets.specific]
name = "dataset1"
mode = "val"
epoch_scale_factor = 1.0
kfold_N = 5
kfold_I = 0

[pl_module.optim]
lr_list = [1e-3, 5e-4, 2e-4, 1e-4, 5e-5]
lr_milestones = [2, 4, 6, 8, 10]

[pl_module.net.specific]
name = "net1"
backbone = "shufflenet"
